### PR TITLE
Added product-listing page to my ecommerce website

### PR DESCRIPTION
**Pull request by Hamza-777**
Please review the PR for the product-listing page and provide feedbacks if any.
Preview: https://festive-bhaskara-70f4e4.netlify.app/html/productlisting.html

### CODE REVIEW

**Review by ApurvaSawant11 — APPROVED** [review]
UI looks good!

Just one change for the rating filter. Since you have `Above` mentioned in it, add a radio button instead of a checkbox

**Comment by Hamza-777** [comment]
> UI looks good!
> 
> Just one change for the rating filter. Since you have `Above` mentioned in it, add a radio button instead of a checkbox

Okay will make the changes apurva. Thanx for the feedback.

**Review by ArjunJunna — APPROVED** [review]
Could fill the space on the right side for UI but if it's intentional then fine. Rest everything is cool.

**Comment by Hamza-777** [comment]
> Could fill the space on the right side for UI but if it's intentional then fine. Rest everything is cool.

Can you point it out?

**Pull request merged**
