### PR TITLE
Added wishlist and cart pages to my ecommerce website.

### PR DESCRIPTION
**Pull request by Hamza-777**
Please review and provide feedback.
Preview Link: https://elastic-aryabhata-db16d8.netlify.app/html/wishlist.html

### CODE REVIEW

**Review by hsnice16 — APPROVED** [review]
The code looks good. Just some suggestions on UI part,

- Change this a/c to page 
image

- white space around the image doesn't look good. The image can cover the whole area 
image

- Also this cross background can be improved, as right now it is very hard to find it. 
image

**Comment by hsnice16** [comment]
Added some suggestions that I notice. Nice work.

**Comment by Hamza-777** [comment]
> Added some suggestions that I notice. Nice work.

Thanks for pointing out himanshu I am working on the solution for these things.

**Review by vishal804 — APPROVED** [review]

**Comment by vishal804** [comment]
Everything Else looks Good

**Comment by Dev-AkshatGupta** [comment]
It seems great to me

**Pull request merged**
